#!/usr/bin/env bash

set -e

export DOTFILES=$HOME/dotfiles

# Include customize printf functions
source $DOTFILES/script/printf

# Check OS
if [ "$(uname -s)" != "Linux" ]
then
  fail "This is for Linux, not $(uname -s)"
fi

# Ask for the administrator password upfront.
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

info "Installing/Updating packages to latest"

# Alias apt-get without confirm prompt.
cmd="sudo apt-get -y"

# Update and Upgrade current packages.
$cmd update
$cmd upgrade

# Install ack-grep
sudo add-apt-repository -y ppa:leonard-ehrenfried/ack2
$cmd update
$cmd install ack-grep
# To create a local diversion, renaming ack-grep to ack
sudo dpkg-divert --local --divert /usr/bin/ack --rename --add /usr/bin/ack-grep

# Install other useful binaries.
$cmd install zsh
$cmd install vim
$cmd install curl
$cmd install wget
$cmd install git
$cmd install git-core
$cmd install ssh
$cmd install tree
$cmd install dos2unix
$cmd install rar unrar
$cmd install zip unzip

# Install other useful binaries to ~/bin
mkdir -p ~/bin
wget https://raw.githubusercontent.com/JakeWharton/pidcat/master/pidcat.py -O ~/bin/pidcat
chmod 755 ~/bin/pidcat

# Install Git Large File Storage (LFS)
if [[ ! $(which git-lfs) ]]; then
  curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  $cmd install git-lfs
  git lfs install
fi

# Remove useless pacakges and downloaded archive files.
$cmd autoremove
$cmd autoclean
