#!/usr/bin/env bash

set -e

export DOTFILES=$HOME/.dotfiles

# Include customize printf functions
source $DOTFILES/script/printf

# Check OS
if [ "$(uname -s)" != "Linux" ]
then
  fail "This is for Linux, not $(uname -s)"
fi

# Run apt-get to install & update packages
$DOTFILES/script/apt-get

# Install software
$DOTFILES/script/install
