#!/usr/bin/env bash

set -e

export DOTFILES=$HOME/.dotfiles

# Include customize printf functions
source $DOTFILES/script/printf

# Check OS
if [ "$(uname -s)" != "Darwin" ]
then
  fail "This is for OS X, not $(uname -s)"
fi

# Set OS X defaults
$DOTFILES/osx/set-defaults.sh

# Install homebrew
$DOTFILES/homebrew/install.sh

# Update homebrew
info "Running brew update"
brew update

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
info "Running brew bundle"
brew bundle

# Install software
$DOTFILES/script/install
