#!/usr/bin/env bash

set -e

export DOTFILES=$HOME/dotfiles

# Include customize printf functions
source $DOTFILES/script/printf

# Check OS
if [ "$(uname -s)" != "Darwin" ]
then
  fail "This is for OS X, not $(uname -s)"
fi

# Ask for the administrator password upfront.
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

info "Installing/Updating packages to latest"

# Make sure we’re using the latest Homebrew.
brew update
# Upgrade any already-installed formulae.
brew upgrade --all

# Install Bash 4.
# Note: don’t forget to add `/usr/local/bin/bash` to `/etc/shells` before
# running `chsh`.
brew install bash
brew tap homebrew/versions
brew install bash-completion2
# Add bash of zsh to /etc/shells
command -v bash | sudo tee -a /etc/shells

# Install vim and override sustem vi.
brew install vim --override-system-vi

# Install other useful binaries.
brew install zsh
brew install curl
brew install wget --with-iri # with IRI support
brew install ack
brew install git
brew install git-lfs
brew install tree
brew install dos2unix
brew install pidcat
#brew install tldr
#brew install mackup

# Install Homebrew-Cask
#brew tap caskroom/cask
#brew cask install google-chrome

# Install Quick Look plugins
brew cask install qlcolorcode
brew cask install qlstephen
brew cask install qlmarkdown
brew cask install quicklook-json
brew cask install qlprettypatch
brew cask install quicklook-csv
brew cask install betterzipql
brew cask install qlimagesize
brew cask install webpquicklook
brew cask install suspicious-package

# Install Caskroom-fonts
brew tap caskroom/fonts
brew cask install font-noto-sans
brew cask install font-roboto
brew cask install font-source-code-pro

# Remove outdated versions from the cellar.
brew cleanup
