#!/usr/bin/env bash

set -e

export DOTFILES=$HOME/dotfiles

# Include customize printf functions
source $DOTFILES/script/printf

# Check OS
if [ "$(uname -s)" != "Darwin" ]
then
  fail "This is for OS X, not $(uname -s)"
fi

# Ask for the administrator password upfront.
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

info "Installing/Updating packages to latest"

# Make sure we’re using the latest Homebrew.
brew update
# Upgrade any already-installed formulae.
brew upgrade

# Install Bash 4.
# Note: don’t forget to add `/usr/local/bin/bash` to `/etc/shells` before running `chsh`.
brew install bash
brew install bash-completion@2
command -v bash | sudo tee -a /etc/shells

# Install general binaries.
brew install vim
brew install zsh
brew install curl
brew install wget
brew install git
brew install git-lfs
#brew install svn
#brew install mercurial
brew install tree
brew install dos2unix
brew install ack # alternative of grep
brew install ripgrep # alternative of grep
brew install bat # alternative of cat
brew install fd # alternative of find
brew install htop # alternative of top
brew install exa # alternative of ls
brew install procs # alternative of ps
brew install sd # alternative of sed
brew install dust # alternative of du
brew install tmux # alternative of screen
brew install zoxide # alternative of cd
brew install tldr
brew install samuel22gj/repo/tldt

# Install development binaries.
brew install pidcat # alternative of logcat
brew install scrcpy
brew install ngrok

# Install Homebrew-Cask
# https://github.com/Homebrew/homebrew-cask
brew tap homebrew/cask
#brew cask install google-chrome

# Install Quick Look plugins
brew install qlcolorcode
brew install qlstephen
brew install qlmarkdown
brew install quicklook-json
brew install quicklook-csv
brew install betterzip
brew install qlimagesize
brew install suspicious-package
brew install quicklookase
brew install qlvideo
brew install provisionql
brew install quicklookapk

# Install Homebrew-Cask-Fonts
# https://github.com/Homebrew/homebrew-cask-fonts
brew tap homebrew/cask-fonts
brew install font-noto-sans
brew install font-roboto
brew install font-source-code-pro
brew install font-noto-mono-for-powerline
brew install font-menlo-for-powerline
brew install font-roboto-mono-for-powerline
brew install font-source-code-pro-for-powerline
brew install font-hack-nerd-font

# Remove outdated versions from the cellar.
brew cleanup
